[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules','lib']
gas_reports = ["LSP6ExecuteRestrictedController", "LSP6ExecuteUnrestrictedController", "LSP6SetDataRestrictedController", "LSP6SetDataUnrestrictedController"]
cache_path = 'forge-cache'
test = 'tests/foundry'
solc_version = "0.8.17"

[fuzz]
runs = 10_000
max_test_rejects = 200_000

[profile.lsp2]
src = 'packages/LSP2ERC725YJSONSchema/contracts'
test = 'packages/LSP2ERC725YJSONSchema/foundry'
out = 'packages/LSP2ERC725YJSONSchema/contracts/foundry_artifacts'
